oil_boiler:
    replacement_factor: 0.8
    
gas_boiler:
    replacement_factor: 0.8

solar_pv:
    potential_integration_factor: 0.8
    
tes_decentralised:
    deployment: true
    capacity_kWh: 300000
    eta_chg_dchg: 1.0 # no charge/discharge losses in virtual storage
    tes_gamma: 0.001 # 0.1%; storage heat loss
    initial_charge: 0.0
    optimized_initial_charge: false
    # connections.solar_thermal: false