district_heating:
  deployment: false
  heat_sources: 
    import: false
    oil_boiler_cp: false

heat_pump:
  deployment: true

electric_heater:
  deployment: true

oil_boiler:
  deployment: false

gas_boiler:
  deployment: false

wood_boiler:
  deployment: false

solar_pvrooftop:
  deployment: true
  only_use_installed: false

solarthermal_rooftop:
  deployment: false

wind_power:
  deployment: false

hydro_power:
  deployment: true

biomass:
  deployment: false

heat_pump_cp:
  deployment: true

oil_boiler_cp:
  deployment: true

grid_supply:
  deployment: true

other:
  deployment: false

bes:
  deployment: false

tes:
  deployment: false

tes_decentralised:
  deployment: false

pile_of_berries':
  deployment: false

gtes:
  deployment: true

ws:
  deployment: true

hes:
  deployment: true 

hydrothermal_gasification:
  deployment: false

anaerobic_digestion_upgrade:
  deployment: false

anaerobic_digestion_upgrade_hydrogen:
  deployment: false

anaerobic_digestion_chp:
  deployment: false

hydrogen_production:
  deployment: false

electric_heater_cp:
  deployment: false

wood_boiler_cp:
  deployment: false